### ISSUE TITLE
Sorting then inserting in again

### ISSUE THREAD

**Issue by lpegoraro** [cloudflare/backgrid#534]
Hi, i am checking this possibilty, I am inserting using the Backbone.Collections comparator, to ensure that the top row is always the last inserted. The headers of my Backgrid are sortable: true, so, after I sort, it changes the behavior and adds the inserted item to the bottom, 

how can I add on top always even after rearrange by sorting in the Backgrid?

I thought it was an issue because it overrides the behavior of insertion. Am I right?

**Comment by wyuenho** [comment]
If you have a comparator, newly inserted rows may be inserted anywhere according to the ordering you've defined. That's the only predefined behavior. To insert on top, you have to remove the comparator.
