### ISSUE TITLE
Release new version (0.3.8)

### ISSUE THREAD

**Issue by n0nick** [cloudflare/backgrid#642]
It's been ~3 months (and [36 commits](https://github.com/wyuenho/backgrid/compare/0.3.7...master)) since 0.3.7 was released.

Would you mind releasing current master as 0.3.8?

In particular, I'm looking forward to merging the bugfix for #564.
Thx!

**Comment by DriesVandermeulen** [comment]
@wyuenho Can we get this moving? It's been almost a year since last release...

**Comment by driesvints** [comment]
@wyuenho please tag a new release.

**Comment by wyuenho** [comment]
Done

**Comment by driesvints** [comment]
Thanks!
