### ISSUE TITLE
API docs site is down

### ISSUE THREAD

**Issue by DavidUnzue** [cloudflare/backgrid#664]
The API docs website under http://wyuenho.github.io/backgrid/api has been down for some time now. When will it be available again? Or where can I browse the API docs now?

P.S.: Travis CI site is down as well

**Comment by wyuenho** [comment]
On it

**Comment by Mefitis** [comment]
Got any info about the issue or ETA of the fix?

**Comment by emileber** [comment]
It's up under the new url: http://cloudflare.github.io/backgrid/api/

But the documentation isn't up to date.

**Comment by emileber** [comment]
@wyuenho this is now solved and could be closed I think.
